<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: guachusperquin
 * Date: Sun, 27 Sep 2015 10:46:43 -0430
 */

$conf['title'] = 'Documentación UCV-Libre';
$conf['lang'] = 'es';
$conf['license'] = 'gnufdl';
$conf['fullpath'] = 1;
$conf['maxtoclevel'] = '4';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['jpg_quality'] = 100;

// end auto-generated content
